import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";
import ThemesProvider from "@/utils/ThemesProvider";
import Header from "../_components/layout/Header/Header";
import Modal from "../_components/layout/Modal/Modal";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import VerificationWrapper from "../_components/layout/VerificationWrapper/VerificationWrapper";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const messages = await getMessages();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistMono.className} antialiased`}>
        <ReduxProvider>
        <NextIntlClientProvider messages={messages}>
            <ThemesProvider>
              <VerificationWrapper>
                <Modal/>
                <header className=""><Header/></header>
                <main className="h-screen">{children}</main>
                <footer></footer>
              </VerificationWrapper>
            </ThemesProvider>
          </NextIntlClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
