import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";
import ThemesProvider from "@/utils/ThemesProvider";
import Header from "../_components/layout/Header/Header";
import Modal from "../_components/layout/Modal/Modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <ThemesProvider>
            <Modal/>
            <header><Header/></header>
            <main>{children}</main>
            <footer></footer>
          </ThemesProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
